markdown: kramdown
baseurl: /FORT-validator
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

fort-latest-version: 1.4.0
